# 构建结构因果图

In [1]:
import os
import re
import pickle
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from time import time
from sklearn.preprocessing import StandardScaler
from IPython.lib.display import IFrame
from causalnex.structure import StructureModel
from causalnex.structure.notears import from_pandas, from_pandas_lasso
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE

## 1. Prepating the Data for Structure Learning

In [12]:
# 读取数据
with open('activity_space_areas_dict.pkl', 'rb') as f:
    act_space_data = pickle.load(f)

print(f"数据中共有 {len(act_space_data)} 个key")

数据中共有 110261 个key

In [13]:
# 将字典转换为DataFrame
data_list = []
for pid, (areas, clusters) in act_space_data.items():
    
    data_list.append({
        'pid': pid,
        'area0': areas[0] if len(areas) > 0 else None,
        'area1': areas[1] if len(areas) > 1 else None,
        'area2': areas[2] if len(areas) > 2 else None,
        'area3': areas[3] if len(areas) > 3 else None,
        'cluster0': clusters[0] if len(clusters) > 0 else None,
        'cluster1': clusters[1] if len(clusters) > 1 else None,
        'cluster2': clusters[2] if len(clusters) > 2 else None,
        'cluster3': clusters[3] if len(clusters) > 3 else None
    })

df = pd.DataFrame(data_list)

# 显示前几行查看结果
df.head()

,pid,area0,area1,area2,area3,cluster0,cluster1,cluster2,cluster3
0,270.0,3.147451,3.308764,3.235937,3.434450,1,1,1,1.0
1,2753.0,3.404565,3.226078,3.234076,3.220988,1,1,1,1.0
2,3203.0,3.352930,3.992503,3.329387,3.443081,2,2,2,2.0
3,4100.0,4.208079,4.887184,5.050174,4.030251,2,2,2,2.0
4,4658.0,3.530046,3.069087,3.043223,3.064848,2,1,1,1.0

In [14]:
# 计算每行的缺失值情况
print("\n各列缺失值统计:")
print(df.isnull().sum())

各列缺失值统计:
pid          0
area0        0
area1        0
area2        0
area3        0
cluster0     0
cluster1     0
cluster2     0
cluster3    29
dtype: int64

In [15]:
# 删除有缺失值的行
df = df.dropna()
print(f"\n删除缺失值后剩余样本量: {len(df)}")

# 将cluster3列转化为int类型
df['cluster3'] = df['cluster3'].astype(int)

删除缺失值后剩余样本量: 110232

In [16]:
# 导入变量信息
variables = pd.read_csv('../../autodl-fs/all_features_v1.csv')
print(variables.columns)

# 连续值建成环境变化
treat_data = pd.read_csv("../../autodl-fs/env_diff.csv")
print("\n建成环境变化量数据：")
print(treat_data.columns)

# # 静态协变量和分类处置变量 - covariance
# covariate = pd.read_csv('../../autodl-fs/df_cov_and_treat.csv')

# # 导入建成环境变量，用于补充静态协变量中的迁居后建成环境数据
# be_data = pd.read_csv('../../autodl-fs/relocate_information_gpd.csv')

Index(['pid', 'year', 'week', 'avg_daily_slow_dist', 'slow_dist_ratio',
       'home_year', 'home_week', 'work_year', 'work_week', 'time', 'home_time',
       'work_time', 'home_density', 'home_landusemix', 'home_road_density',
       'home_openratio_wide', 'home_subway', 'home_bus', 'home_center',
       'work_density', 'work_landusemix', 'work_road_density',
       'work_openratio_wide', 'work_subway', 'work_bus', 'work_center',
       'commute_distance', 'gender', 'age', 'edu', 'married', 'income', 'z_0',
       'z_1', 'home_density_label', 'home_landusemix_label',
       'home_road_density_label', 'home_openratio_wide_label',
       'home_subway_label', 'home_bus_label', 'home_center_label',
       'work_density_label', 'work_landusemix_label',
       'work_road_density_label', 'work_openratio_wide_label',
       'work_subway_label', 'work_bus_label', 'work_center_label',
       'home_change', 'work_change', 'state', 'weekly_R24H', 'weekly_AVGT',
       'is_workweek', 'previous_avg_daily_slow_dist',
       'previous_slow_dist_ratio'],
      dtype='object')

建成环境变化量数据：
Index(['pid', 'home_density', 'home_landusemix', 'home_road_density',
       'home_openratio_wide', 'home_subway', 'home_bus', 'home_center',
       'work_density', 'work_landusemix', 'work_road_density',
       'work_openratio_wide', 'work_subway', 'work_bus', 'work_center'],
      dtype='object')

In [17]:
print(variables['pid'].nunique())
print(treat_data['pid'].nunique())

138032
147440

In [18]:
# 计算df和variables的pid重合情况
df_pid_set = set(df['pid'])
variables_pid_set = set(variables['pid'])
treat_data_pid_set = set(treat_data['pid'])

print("df和variables的pid重合情况:")
print(f"df中的pid数量: {len(df_pid_set)}")
print(f"variables中的pid数量: {len(variables_pid_set)}")
print(f"重合的pid数量: {len(df_pid_set.intersection(variables_pid_set))}")

print("\ndf和treat_data的pid重合情况:")
print(f"df中的pid数量: {len(df_pid_set)}")
print(f"treat_data中的pid数量: {len(treat_data_pid_set)}")
print(f"重合的pid数量: {len(df_pid_set.intersection(treat_data_pid_set))}")

df和variables的pid重合情况:
df中的pid数量: 110232
variables中的pid数量: 138032
重合的pid数量: 84860

df和treat_data的pid重合情况:
df中的pid数量: 110232
treat_data中的pid数量: 147440
重合的pid数量: 84860

In [19]:
# 选取df中与variables和treat_data都重合的pid
common_pid = df_pid_set.intersection(variables_pid_set).intersection(treat_data_pid_set)
print(f"\n三个数据集共同的pid数量: {len(common_pid)}")

# 筛选出共同的pid
df = df[df['pid'].isin(common_pid)].reset_index(drop=True)
print(f"筛选后df的样本量: {len(df)}")

三个数据集共同的pid数量: 84860
筛选后df的样本量: 84860

用84,860样本也可以

### 选取需要的列

In [3]:
be_cols = ['home_density', 'home_landusemix', 'home_road_density',
       'home_openratio_wide', 'home_subway', 'home_bus', 'home_center',
       'work_density', 'work_landusemix', 'work_road_density',
       'work_openratio_wide', 'work_subway', 'work_bus', 'work_center',
       'commute_distance']

user_cols = ['gender', 'age', 'edu', 'married', 'income', 'state', 'z_0', 'z_1'] #加上两个混淆替代，看看效果？

In [21]:
# 按pid和time升序排序
variables = variables.sort_values(['pid', 'time'])

# 提取每个pid的第一行和最后一行的建成环境数据
be_0 = variables.groupby('pid')[be_cols].first().reset_index()
be_1 = variables.groupby('pid')[be_cols].last().reset_index()

# 重命名列,添加后缀
be_0.columns = ['pid'] + [col + '_0' for col in be_cols]
be_1.columns = ['pid'] + [col + '_1' for col in be_cols]

# 提取每个pid的第一行的用户特征数据
user_features = variables.groupby('pid')[user_cols].first().reset_index()

# 合并数据
features_df = pd.merge(be_0, be_1, on='pid')
features_df = pd.merge(features_df, user_features, on='pid')

features_df.head()

,pid,home_density_0,home_landusemix_0,home_road_density_0,home_openratio_wide_0,home_subway_0,home_bus_0,home_center_0,work_density_0,work_landusemix_0,...,work_center_1,commute_distance_1,gender,age,edu,married,income,state,z_0,z_1
0,263.0,19.180278,0.674795,28.261657,0.229073,0.000000,0.646465,4.266739,9.033984,0.785131,...,9.644711,1.828381,1,1,0.042208,0.364399,1,1,1.115773,-0.136993
1,270.0,14.529677,0.618902,38.814044,0.050432,0.000000,0.177778,3.473704,23.875621,0.577250,...,10.653325,0.190520,1,1,0.019883,0.497199,0,1,-0.318092,0.054852
2,2753.0,43.323924,0.731403,21.825231,0.021142,0.000000,10.666667,9.977737,25.321366,0.679151,...,9.977737,1.431244,2,2,0.064334,0.533578,0,1,-0.951096,0.132268
3,3605.0,72.557727,0.716023,34.220444,0.006849,0.000000,10.666667,0.726368,11.029024,0.599132,...,2.553382,5.859032,1,1,0.185533,0.485299,1,0,-1.581614,0.670394
4,4100.0,32.723039,0.688787,29.601778,0.041243,1.185185,11.851852,9.260486,0.024889,0.802058,...,6.693424,9.135008,1,1,0.084597,0.329650,1,1,-1.128722,0.139727

In [22]:
# 根据pid关联df和features_df
df = pd.merge(df, features_df, on='pid', how='left')
df.head()

,pid,area0,area1,area2,area3,cluster0,cluster1,cluster2,cluster3,home_density_0,...,work_center_1,commute_distance_1,gender,age,edu,married,income,state,z_0,z_1
0,270.0,3.147451,3.308764,3.235937,3.434450,1,1,1,1,14.529677,...,10.653325,0.190520,1,1,0.019883,0.497199,0,1,-0.318092,0.054852
1,2753.0,3.404565,3.226078,3.234076,3.220988,1,1,1,1,43.323924,...,9.977737,1.431244,2,2,0.064334,0.533578,0,1,-0.951096,0.132268
2,4100.0,4.208079,4.887184,5.050174,4.030251,2,2,2,2,32.723039,...,6.693424,9.135008,1,1,0.084597,0.329650,1,1,-1.128722,0.139727
3,4658.0,3.530046,3.069087,3.043223,3.064848,2,1,1,1,26.280335,...,11.444046,0.536638,1,1,0.283376,0.357079,2,1,-0.465670,0.074777
4,4942.0,3.458569,5.794304,3.526932,3.464373,2,2,1,2,21.517534,...,6.615958,3.437476,1,2,0.410029,0.596804,3,1,-0.229027,0.062306

In [23]:
# 计算包含nan的行数
nan_rows = df.isna().any(axis=1).sum()
print(f"包含nan值的行数: {nan_rows}")

包含nan值的行数: 0

In [24]:
# 从treat_data中选取建成环境变量的变化量
treat_data.rename(columns={col: col + '_change' for col in be_cols}, inplace=True)
df = pd.merge(df, treat_data, on='pid', how='left')

nan_rows = df.isna().any(axis=1).sum()
print(f"包含nan值的行数: {nan_rows}")

包含nan值的行数: 0

In [25]:
# 保存一下
df.to_csv('../data/act_space_features.csv', index=False)

## 2. Apply the NOTEARS algorithm to learn the structure

In [2]:
# 导入df
# df = pd.read_csv('../data/act_space_features.csv')
df = pd.read_csv('../data/act_space_travel_features.csv')

# 删除pid列
df = df.drop('pid', axis=1)

# 删除be_change列和两个潜在替代
treat_cols = ['home_density_change','home_landusemix_change','home_road_density_change','home_openratio_wide_change', 
              'home_subway_change','home_bus_change','home_center_change','work_density_change','work_landusemix_change',
              'work_road_density_change','work_openratio_wide_change','work_subway_change','work_bus_change','work_center_change']
# treat_cols = []
df = df.drop(columns=treat_cols+['z_0','z_1'])

参考Wang2019的论文，出行变量选择：
1. Total travel time
2. Slow trip frequency
3. Subway trip frequency

因此删除avg_daily_dist, avg_daily_tube_dist, avg_daily_slow_dist试试
* **删除之后结果不好！**

In [100]:
# 定义需要删除的列前缀
# drop_travel_cols = ['avg_daily_dur']

# # 使用 list comprehension 和 filter 来获取匹配的列
# cols_to_drop = [col for col in df.columns if any(col.startswith(prefix) for prefix in drop_travel_cols)]

# # 删除这些列
# df = df.drop(columns=cols_to_drop)

# print(df.columns)

In [3]:
# 对非int类型的列进行标准化
numeric_cols = df.select_dtypes(include=['float64']).columns
scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

df.head()

,area0,area1,area2,area3,cluster0,cluster1,cluster2,cluster3,home_density_0,home_landusemix_0,...,avg_daily_slow_freq2,avg_daily_slow_freq3,avg_daily_tube_dist0,avg_daily_tube_dist1,avg_daily_tube_dist2,avg_daily_tube_dist3,avg_daily_tube_freq0,avg_daily_tube_freq1,avg_daily_tube_freq2,avg_daily_tube_freq3
0,-0.744687,-0.608889,-0.692689,-0.509501,1,1,1,1,-0.885528,-0.611027,...,-0.517820,-0.507870,-0.912620,-0.893552,-0.905257,-0.913905,-1.115959,-1.068603,-1.119792,-1.101909
1,-0.480117,-0.683268,-0.694503,-0.728679,1,1,1,1,0.256275,0.735790,...,-0.696064,-0.701271,0.024985,0.017771,-0.372836,-0.329942,-0.517611,-0.507939,-0.469989,-0.441959
2,0.346698,0.810954,1.074974,0.102256,2,2,2,2,-0.164091,0.225602,...,-0.606139,-0.406450,0.584033,0.056909,-0.031343,0.180311,0.512307,0.123323,0.305134,0.894306
3,-0.350997,-0.824487,-0.880456,-0.889001,2,1,1,1,-0.419569,-0.048852,...,-0.747303,-0.740707,0.222559,0.875306,0.274114,0.255988,0.146706,0.694621,-0.176184,-0.266391
4,-0.424547,1.626939,-0.409164,-0.478776,2,2,1,2,-0.608432,1.129840,...,-0.080472,-0.353129,-0.912620,-0.893552,-0.844739,-0.847529,-1.115959,-1.068603,-0.859871,-0.837929

### Area + Cluster

设定规则：
1. 调整后的活动空间不作为父节点（感兴趣的outcomes）
2. 一些个人属性（age, gender）不可作为子节点

In [4]:
t0 = time()

sm = from_pandas(df, tabu_parent_nodes=['area2','area3', 'cluster2','cluster3'],tabu_child_nodes=['age', 'gender'], w_threshold=0.02)
print(f'Running NOTEARS algorithm takes {time() - t0} seconds')

Running NOTEARS algorithm takes 156.24037098884583 seconds

In [5]:
viz = plot_structure(
    sm,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)
viz.show("supporting_files/00_initial_graph.html")

supporting_files/00_initial_graph.html

In [6]:
sm_subgraph = sm.get_largest_subgraph()
viz = plot_structure(
    sm_subgraph,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)
viz.show("supporting_files/00_largest_subgraph.html")

supporting_files/00_largest_subgraph.html

In [4]:
# 把cluster和area分开求解
df_area = df.drop(columns = ['cluster0', 'cluster1', 'cluster2', 'cluster3'])
df_cluster = df.drop(columns = ['area0', 'area1', 'area2', 'area3'])

### Area Causal Path

In [22]:
sm_area = from_pandas(df_area)

In [5]:
# sm_area = from_pandas(df_area, tabu_parent_nodes=['area0','area1','area2','area3'])
sm_area = from_pandas(df_area, tabu_parent_nodes=['area2','area3'])

In [6]:
print(sm_area.adj)

{'area0': {}, 'area1': {}, 'area2': {}, 'area3': {}, 'home_density_0': {'area0': {'origin': 'learned', 'weight': 0.002701812793478628}, 'area1': {'origin': 'learned', 'weight': 0.0015345652850422826}, 'area2': {'origin': 'learned', 'weight': 0.0010476506660405999}, 'area3': {'origin': 'learned', 'weight': 0.005548982047078525}, 'home_landusemix_0': {'origin': 'learned', 'weight': -0.0004714085444269733}, 'home_road_density_0': {'origin': 'learned', 'weight': 0.008421103853292929}, 'home_openratio_wide_0': {'origin': 'learned', 'weight': -0.006208479938883276}, 'home_subway_0': {'origin': 'learned', 'weight': 0.0009644809660208216}, 'home_bus_0': {'origin': 'learned', 'weight': -0.000448214568630643}, 'home_center_0': {'origin': 'learned', 'weight': -0.006396041486483252}, 'work_density_0': {'origin': 'learned', 'weight': 0.00011399895529959281}, 'work_landusemix_0': {'origin': 'learned', 'weight': 0.0018811029860441083}, 'work_road_density_0': {'origin': 'learned', 'weight': 0.005476725532399893}, 'work_openratio_wide_0': {'origin': 'learned', 'weight': 0.00038770644159200025}, 'work_subway_0': {'origin': 'learned', 'weight': 0.004417443702278564}, 'work_bus_0': {'origin': 'learned', 'weight': 0.003692087125826086}, 'work_center_0': {'origin': 'learned', 'weight': -0.0030395599071492804}, 'commute_distance_0': {'origin': 'learned', 'weight': 0.0018628423305650174}, 'home_density_1': {'origin': 'learned', 'weight': 0.006535590081052842}, 'home_landusemix_1': {'origin': 'learned', 'weight': -0.0007550798838428102}, 'home_road_density_1': {'origin': 'learned', 'weight': 0.001741165479951331}, 'home_openratio_wide_1': {'origin': 'learned', 'weight': -8.12785074026234e-05}, 'home_subway_1': {'origin': 'learned', 'weight': 0.0011395179419650195}, 'home_bus_1': {'origin': 'learned', 'weight': -0.00013807496989568684}, 'home_center_1': {'origin': 'learned', 'weight': -0.004020089743347376}, 'work_density_1': {'origin': 'learned', 'weight': 0.000129474922596702}, 'work_landusemix_1': {'origin': 'learned', 'weight': 0.001860042611140364}, 'work_road_density_1': {'origin': 'learned', 'weight': 0.004864703962045236}, 'work_openratio_wide_1': {'origin': 'learned', 'weight': -0.0008970124796828729}, 'work_subway_1': {'origin': 'learned', 'weight': 0.003986654827748334}, 'work_bus_1': {'origin': 'learned', 'weight': 0.003504742609261465}, 'work_center_1': {'origin': 'learned', 'weight': -0.0031937196295080635}, 'commute_distance_1': {'origin': 'learned', 'weight': 0.002026210483296402}, 'gender': {'origin': 'learned', 'weight': 0.00046527070051365755}, 'age': {'origin': 'learned', 'weight': -0.0002103999986065388}, 'edu': {'origin': 'learned', 'weight': 2.006684423696969e-05}, 'married': {'origin': 'learned', 'weight': 1.563910422004966e-05}, 'income': {'origin': 'learned', 'weight': -0.01124592140754338}, 'state': {'origin': 'learned', 'weight': 0.0001356328891388616}, 'z_0': {'origin': 'learned', 'weight': -0.012552974560442505}, 'z_1': {'origin': 'learned', 'weight': -0.0007446139399636347}, 'avg_daily_dist0': {'origin': 'learned', 'weight': -0.0004915972528289107}, 'avg_daily_dist1': {'origin': 'learned', 'weight': -0.00036386436701917724}, 'avg_daily_dist2': {'origin': 'learned', 'weight': -0.0005281785616059531}, 'avg_daily_dist3': {'origin': 'learned', 'weight': -0.0009006340326277616}, 'avg_daily_dur0': {'origin': 'learned', 'weight': -0.0030814011378720537}, 'avg_daily_dur1': {'origin': 'learned', 'weight': -0.003215543277940808}, 'avg_daily_dur2': {'origin': 'learned', 'weight': -0.0033618326996649015}, 'avg_daily_dur3': {'origin': 'learned', 'weight': -0.0031865553914480465}, 'avg_daily_slow_dist0': {'origin': 'learned', 'weight': -0.00475866465048296}, 'avg_daily_slow_dist1': {'origin': 'learned', 'weight': -0.004646380412097866}, 'avg_daily_slow_dist2': {'origin': 'learned', 'weight': -0.004448576853459925}, 'avg_daily_slow_dist3': {'origin': 'learned', 'weight': -0.004136600251579068}, 'avg_daily_slow_freq0': {'origin': 'learned', 'weight': -0.005415948897771707}, 'avg_daily_slow_freq1': {'origin': 'learned', 'weight': -0.005070513840812449}, 'avg_daily_slow_freq2': {'origin': 'learned', 'weight': -0.0038699661157865265}, 'avg_daily_slow_freq3': {'origin': 'learned', 'weight': -0.003410209425712181}, 'avg_daily_tube_dist0': {'origin': 'learned', 'weight': 0.009537806985109436}, 'avg_daily_tube_dist1': {'origin': 'learned', 'weight': 0.009852274387569845}, 'avg_daily_tube_dist2': {'origin': 'learned', 'weight': 0.009158180173964359}, 'avg_daily_tube_dist3': {'origin': 'learned', 'weight': 0.008855842922150884}, 'avg_daily_tube_freq0': {'origin': 'learned', 'weight': 0.020669230046758167}, 'avg_daily_tube_freq1': {'origin': 'learned', 'weight': 0.02003865286514075}, 'avg_daily_tube_freq2': {'origin': 'learned', 'weight': 0.017951147712482476}, 'avg_daily_tube_freq3': {'origin': 'learned', 'weight': 0.017052600658594232}}, 'home_landusemix_0': {'area0': {'origin': 'learned', 'weight': -0.0028964859517540136}, 'area1': {'origin': 'learned', 'weight': -0.00016254622803135802}, 'area2': {'origin': 'learned', 'weight': 0.002158262104882716}, 'area3': {'origin': 'learned', 'weight': 0.0028801032800752583}, 'home_density_0': {'origin': 'learned', 'weight': -0.001147416804944037}, 'home_road_density_0': {'origin': 'learned', 'weight': 0.011663527227149856}, 'home_openratio_wide_0': {'origin': 'learned', 'weight': -0.009370126538755531}, 'home_subway_0': {'origin': 'learned', 'weight': -0.00047429768189273037}, 'home_bus_0': {'origin': 'learned', 'weight': 0.013792939170618045}, 'home_center_0': {'origin': 'learned', 'weight': -0.0039061374841645384}, 'work_density_0': {'origin': 'learned', 'weight': 0.00044472144925554333}, 'work_landusemix_0': {'origin': 'learned', 'weight': 0.008768996044952935}, 'work_road_density_0': {'origin': 'learned', 'weight': 0.004342827945141935}, 'work_openratio_wide_0': {'origin': 'learned', 'weight': -0.0014003103063880383}, 'work_subway_0': {'origin': 'learned', 'weight': 0.002352679048723489}, 'work_bus_0': {'origin': 'learned', 'weight': 0.004764601888404804}, 'work_center_0': {'origin': 'learned', 'weight': -0.003314241866359598}, 'commute_distance_0': {'origin': 'learned', 'weight': -0.0009657468953617787}, 'home_density_1': {'origin': 'learned', 'weight': -0.0010906454674078651}, 'home_landusemix_1': {'origin': 'learned', 'weight': 0.005190072145698476}, 'home_road_density_1': {'origin': 'learned', 'weight': 0.00559949409408293}, 'home_openratio_wide_1': {'origin': 'learned', 'weight': -0.00024947567880861243}, 'home_subway_1': {'origin': 'learned', 'weight': 0.00293447394411734}, 'home_bus_1': {'origin': 'learned', 'weight': 0.005618080286275416}, 'home_center_1': {'origin': 'learned', 'weight': -0.0054196899144942105}, 'work_density_1': {'origin': 'learned', 'weight': -0.0001410840774064186}, 'work_landusemix_1': {'origin': 'learned', 'weight': 0.006964453690451279}, 'work_road_density_1': {'origin': 'learned', 'weight': 0.0038263424823762235}, 'work_openratio_wide_1': {'origin': 'learned', 'weight': -0.002314299159528409}, 'work_subway_1': {'origin': 'learned', 'weight': 0.0024360086324436325}, 'work_bus_1': {'origin': 'learned', 'weight': 0.0038125361856667355}, 'work_center_1': {'origin': 'learned', 'weight': -0.003684386078866718}, 'commute_distance_1': {'origin': 'learned', 'weight': 0.0003048626615523425}, 'gender': {'origin': 'learned', 'weight': -0.00010706571471704942}, 'age': {'origin': 'learned', 'weight': -0.0003522356815251763}, 'edu': {'origin': 'learned', 'weight': 0.0036581618025349188}, 'married': {'origin': 'learned', 'weight': 3.706782144978182e-05}, 'income': {'origin': 'learned', 'weight': 0.0030535232034561745}, 'state': {'origin': 'learned', 'weight': 0.0006141380579774963}, 'z_0': {'origin': 'learned', 'weight': -8.258268907149153e-05}, 'z_1': {'origin': 'learned', 'weight': -0.0006146899825728048}, 'avg_daily_dist0': {'origin': 'learned', 'weight': -0.0014185959710515297}, 'avg_daily_dist1': {'origin': 'learned', 'weight': -0.0013314785280839113}, 'avg_daily_dist2': {'origin': 'learned', 'weight': 0.00041647275665523405}, 'avg_daily_dist3': {'origin': 'learned', 'weight': 8.578999622602827e-06}, 'avg_daily_dur0': {'origin': 'learned', 'weight': -0.0014343578914590908}, 'avg_daily_dur1': {'origin': 'learned', 'weight': -0.0013436597372053162}, 'avg_daily_dur2': {'origin': 'learned', 'weight': -0.0009387343675583039}, 'avg_daily_dur3': {'origin': 'learned', 'weight': -0.0007494363030812418}, 'avg_daily_slow_dist0': {'origin': 'learned', 'weight': -0.0006396872091715966}, 'avg_daily_slow_dist1': {'origin': 'learned', 'weight': -0.0005306640313307558}, 'avg_daily_slow_dist2': {'origin': 'learned', 'weight': 0.00015720410448009356}, 'avg_daily_slow_dist3': {'origin': 'learned', 'weight': -0.00023331218127253228}, 'avg_daily_slow_freq0': {'origin': 'learned', 'weight': 0.000832453890649693}, 'avg_daily_slow_freq1': {'origin': 'learned', 'weight': 0.0008457382993675351}, 'avg_daily_slow_freq2': {'origin': 'learned', 'weight': 0.0010810259980413306}, 'avg_daily_slow_freq3': {'origin': 'learned', 'weight': 0.0007663871019382262}, 'avg_daily_tube_dist0': {'origin': 'learned', 'weight': -0.0015243769520748485}, 'avg_daily_tube_dist1': {'origin': 'learned', 'weight': -0.001524421318572553}, 'avg_daily_tube_dist2': {'origin': 'learned', 'weight': -0.0011401045617161422}, 'avg_daily_tube_dist3': {'origin': 'learned', 'weight': -0.0014304570054551446}, 'avg_daily_tube_freq0': {'origin': 'learned', 'weight': 0.0001382727435733975}, 'avg_daily_tube_freq1': {'origin': 'learned', 'weight': 0.00016712332701763547}, 'avg_daily_tube_freq2': {'origin': 'learned', 'weight': 0.00019587384585429457}, 'avg_daily_tube_freq3': {'origin': 'learned', 'weight': 0.0003701051244351852}}, 'home_road_density_0': {'area0': {'origin': 'learned', 'weight': -0.0036670624295328104}, 'area1': {'origin': 'learned', 'weight': -0.002589886985131949}, 'area2': {'origin': 'learned', 'weight': 0.0008384442760658642}, 'area3': {'origin': 'learned', 'weight': 0.002702118352452352}, 'home_density_0': {'origin': 'learned', 'weight': 2.8652871435036666e-05}, 'home_landusemix_0': {'origin': 'learned', 'weight': 0.0001170195719749767}, 'home_openratio_wide_0': {'origin': 'learned', 'weight': 7.215523343272515e-05}, 'home_subway_0': {'origin': 'learned', 'weight': 7.153523343021952e-05}, 'home_bus_0': {'origin': 'learned', 'weight': 5.190652682443803e-05}, 'home_center_0': {'origin': 'learned', 'weight': 3.91242960368268e-06}, 'work_density_0': {'origin': 'learned', 'weight': 0.0005899378209337115}, 'work_landusemix_0': {'origin': 'learned', 'weight': -0.0003520751612745802}, 'work_road_density_0': {'origin': 'learned', 'weight': 0.0037551627296806772}, 'work_openratio_wide_0': {'origin': 'learned', 'weight': -0.00010808547638117941}, 'work_subway_0': {'origin': 'learned', 'weight': 0.001150532046111321}, 'work_bus_0': {'origin': 'learned', 'weight': 0.004032509497088139}, 'work_center_0': {'origin': 'learned', 'weight': -0.0013903563584641337}, 'commute_distance_0': {'origin': 'learned', 'weight': -0.0004075456631462094}, 'home_density_1': {'origin': 'learned', 'weight': 0.0013859617825153355}, 'home_landusemix_1': {'origin': 'learned', 'weight': -7.528602304491072e-05}, 'home_road_density_1': {'origin': 'learned', 'weight': 9.100636712885911e-05}, 'home_openratio_wide_1': {'origin': 'learned', 'weight': -0.0001290348394904993}, 'home_subway_1': {'origin': 'learned', 'weight': -0.0002748125613254663}, 'home_bus_1': {'origin': 'learned', 'weight': 0.00013109643135187835}, 'home_center_1': {'origin': 'learned', 'weight': -0.002690455630520931}, 'work_density_1': {'origin': 'learned', 'weight': 0.001162250413185232}, 'work_landusemix_1': {'origin': 'learned', 'weight': 0.0003391032830320289}, 'work_road_density_1': {'origin': 'learned', 'weight': 0.006994261550780501}, 'work_openratio_wide_1': {'origin': 'learned', 'weight': 0.00018110793794754232}, 'work_subway_1': {'origin': 'learned', 'weight': 0.001492577696168085}, 'work_bus_1': {'origin': 'learned', 'weight': 0.0034510746639217407}, 'work_center_1': {'origin': 'learned', 'weight': -0.0018765711610008843}, 'commute_distance_1': {'origin': 'learned', 'weight': 0.00126894073681297}, 'gender': {'origin': 'learned', 'weight': -0.0007375075307214498}, 'age': {'origin': 'learned', 'weight': -0.0006420352292749842}, 'edu': {'origin': 'learned', 'weight': 7.018030572161199e-05}, 'married': {'origin': 'learned', 'weight': 8.596465817827338e-05}, 'income': {'origin': 'learned', 'weight': 0.022057151849583453}, 'state': {'origin': 'learned', 'weight': 0.00048779221706057657}, 'z_0': {'origin': 'learned', 'weight': -0.00697585303039408}, 'z_1': {'origin': 'learned', 'weight': -0.00032173710473357175}, 'avg_daily_dist0': {'origin': 'learned', 'weight': -0.001825856009070365}, 'avg_daily_dist1': {'origin': 'learned', 'weight': -0.0015472118624228288}, 'avg_daily_dist2': {'origin': 'learned', 'weight': 0.0007288966792803463}, 'avg_daily_dist3': {'origin': 'learned', 'weight': 0.0008007183032318474}, 'avg_daily_dur0': {'origin': 'learned', 'weight': -0.0017580137662479296}, 'avg_daily_dur1': {'origin': 'learned', 'weight': -0.0013922091898392992}, 'avg_daily_dur2': {'origin': 'learned', 'weight': -0.0010917976874049347}, 'avg_daily_dur3': {'origin': 'learned', 'weight': -0.0004740322051818524}, 'avg_daily_slow_dist0': {'origin': 'learned', 'weight': 0.0014661239108201632}, 'avg_daily_slow_dist1': {'origin': 'learned', 'weight': 0.0009486660091451983}, 'avg_daily_slow_dist2': {'origin': 'learned', 'weight': -0.0006532891600924937}, 'avg_daily_slow_dist3': {'origin': 'learned', 'weight': -0.00025520273882060024}, 'avg_daily_slow_freq0': {'origin': 'learned', 'weight': 0.0008951549726346009}, 'avg_daily_slow_freq1': {'origin': 'learned', 'weight': 0.0010474024527507226}, 'avg_daily_slow_freq2': {'origin': 'learned', 'weight': -0.001013510235519589}, 'avg_daily_slow_freq3': {'origin': 'learned', 'weight': -0.0008987414729564749}, 'avg_daily_tube_dist0': {'origin': 'learned', 'weight': -0.000451178158375466}, 'avg_daily_tube_dist1': {'origin': 'learned', 'weight': -0.0009572016049288845}, 'avg_daily_tube_dist2': {'origin': 'learned', 'weight': 0.0017367513221957793}, 'avg_daily_tube_dist3': {'origin': 'learned', 'weight': 0.0022780116955606914}, 'avg_daily_tube_freq0': {'origin': 'learned', 'weight': -1.1524849032472591e-05}, 'avg_daily_tube_freq1': {'origin': 'learned', 'weight': 1.9735072809193726e-05}, 'avg_daily_tube_freq2': {'origin': 'learned', 'weight': 0.002321788204168445}, 'avg_daily_tube_freq3': {'origin': 'learned', 'weight': 0.0023388429304636847}}, 'home_openratio_wide_0': {'area0': {'origin': 'learned', 'weight': 0.00934106541158369}, 'area1': {'origin': 'learned', 'weight': 0.004425285381723453}, 'area2': {'origin': 'learned', 'weight': 0.0007997932764215362}, 'area3': {'origin': 'learned', 'weight': -0.0018674854361926884}, 'home_density_0': {'origin': 'learned', 'weight': -7.983464551230658e-05}, 'home_landusemix_0': {'origin': 'learned', 'weight': 1.5324249186018785e-05}, 'home_road_density_0': {'origin': 'learned', 'weight': -0.0028853226663409864}, 'home_subway_0': {'origin': 'learned', 'weight': -8.088993643927788e-05}, 'home_bus_0': {'origin': 'learned', 'weight': -4.303817404129724e-05}, 'home_center_0': {'origin': 'learned', 'weight': 3.35237097542737e-05}, 'work_density_0': {'origin': 'learned', 'weight': 5.942718248155715e-05}, 'work_landusemix_0': {'origin': 'learned', 'weight': -0.0008939375460612008}, 'work_road_density_0': {'origin': 'learned', 'weight': -0.003010784334524348}, 'work_openratio_wide_0': {'origin': 'learned', 'weight': 0.00010685489622767804}, 'work_subway_0': {'origin': 'learned', 'weight': -0.0023303131948418996}, 'work_bus_0': {'origin': 'learned', 'weight': -0.001781483093073266}, 'work_center_0': {'origin': 'learned', 'weight': 0.0007039907325629575}, 'commute_distance_0': {'origin': 'learned', 'weight': -4.348741467107871e-06}, 'home_density_1': {'origin': 'learned', 'weight': -0.011357976038924357}, 'home_landusemix_1': {'origin': 'learned', 'weight': -0.001659636865404239}, 'home_road_density_1': {'origin': 'learned', 'weight': -0.006969186789142234}, 'home_openratio_wide_1': {'origin': 'learned', 'weight': -0.00034351406474988563}, 'home_subway_1': {'origin': 'learned', 'weight': -0.0032622108119950625}, 'home_bus_1': {'origin': 'learned', 'weight': -0.002096302978329661}, 'home_center_1': {'origin': 'learned', 'weight': 0.0017555245376131056}, 'work_density_1': {'origin': 'learned', 'weight': -0.0008680852112634839}, 'work_landusemix_1': {'origin': 'learned', 'weight': -0.0013712630305679806}, 'work_road_density_1': {'origin': 'learned', 'weight': -0.003338506856328971}, 'work_openratio_wide_1': {'origin': 'learned', 'weight': 0.0057942333589346175}, 'work_subway_1': {'origin': 'learned', 'weight': -0.002477624497976691}, 'work_bus_1': {'origin': 'learned', 'weight': -0.002347721800391273}, 'work_center_1': {'origin': 'learned', 'weight': 0.0015580512229409734}, 'commute_distance_1': {'origin': 'learned', 'weight': -0.0011219989834593872}, 'gender': {'origin': 'learned', 'weight': -0.0005404072155793352}, 'age': {'origin': 'learned', 'weight': 2.3208531874859983e-05}, 'edu': {'origin': 'learned', 'weight': -2.960739902923388e-05}, 'married': {'origin': 'learned', 'weight': -5.5121631370274174e-05}, 'income': {'origin': 'learned', 'weight': 0.000989303128234566}, 'state': {'origin': 'learned', 'weight': -7.733000572639036e-05}, 'z_0': {'origin': 'learned', 'weight': 8.578313047848656e-05}, 'z_1': {'origin': 'learned', 'weight': 0.00041325920617899165}, 'avg_daily_dist0': {'origin': 'learned', 'weight': 0.0009106034762025238}, 'avg_daily_dist1': {'origin': 'learned', 'weight': 0.0009130764521750362}, 'avg_daily_dist2': {'origin': 'learned', 'weight': 0.0011455706880937324}, 'avg_daily_dist3': {'origin': 'learned', 'weight': 0.0014389368752406111}, 'avg_daily_dur0': {'origin': 'learned', 'weight': 0.00308549064615165}, 'avg_daily_dur1': {'origin': 'learned', 'weight': 0.003013480647026915}, 'avg_daily_dur2': {'origin': 'learned', 'weight': 0.0033916442486481143}, 'avg_daily_dur3': {'origin': 'learned', 'weight': 0.003033180779236592}, 'avg_daily_slow_dist0': {'origin': 'learned', 'weight': 0.004069003610760143}, 'avg_daily_slow_dist1': {'origin': 'learned', 'weight': 0.00391319545191905}, 'avg_daily_slow_dist2': {'origin': 'learned', 'weight': 0.003245882295767381}, 'avg_daily_slow_dist3': {'origin': 'learned', 'weight': 0.002981760232252091}, 'avg_daily_slow_freq0': {'origin': 'learned', 'weight': 0.003383115437936672}, 'avg_daily_slow_freq1': {'origin': 'learned', 'weight': 0.0033266453755487623}, 'avg_daily_slow_freq2': {'origin': 'learned', 'weight': 0.0025287113077837923}, 'avg_daily_slow_freq3': {'origin': 'learned', 'weight': 0.0021632671794481885}, 'avg_daily_tube_dist0': {'origin': 'learned', 'weight': -0.004668854405930741}, 'avg_daily_tube_dist1': {'origin': 'learned', 'weight': -0.004695868619389352}, 'avg_daily_tube_dist2': {'origin': 'learned', 'weight': -0.003794837571906545}, 'avg_daily_tube_dist3': {'origin': 'learned', 'weight': -0.003686118273098346}, 'avg_daily_tube_freq0': {'origin': 'learned', 'weight': -0.006863991665132394}, 'avg_daily_tube_freq1': {'origin': 'learned', 'weight': -0.006756750002821092}, 'avg_daily_tube_freq2': {'origin': 'learned', 'weight': -0.005681884339535161}, 'avg_daily_tube_freq3': {'origin': 'learned', 'weight': -0.0052286073059283995}}, 'home_subway_0': {'area0': {'origin': 'learned', 'weight': -0.007774426006424571}, 'area1': {'origin': 'learned', 'weight': -0.0033099693434889216}, 'area2': {'origin': 'learned', 'weight': -0.002157960678179997}, 'area3': {'origin': 'learned', 'weight': -0.0006543909086835427}, 'home_density_0': {'origin': 'learned', 'weight': 0.0013328657243691965}, 'home_landusemix_0': {'origin': 'learned', 'weight': 0.003940566893400094}, 'home_road_density_0': {

visualise the learned StructureModel using the plot function.

In [10]:
viz = plot_structure(
    sm_area,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.toggle_physics(False)
viz.show("supporting_files/01_fully_connected.html")

supporting_files/01_fully_connected.html

#### **apply threshold**

In [19]:
weight_thre = 0.02

In [20]:
sm_area.remove_edges_below_threshold(weight_thre)

viz = plot_structure(
    sm_area,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)
# viz.toggle_physics(False)
viz.show("supporting_files/01_thresholded.html")

supporting_files/01_thresholded.html

#### **最大子图**

In [21]:
sm_area_subgraph = sm_area.get_largest_subgraph()
viz = plot_structure(
    sm_area_subgraph,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)
viz.show("supporting_files/01_largest_subgraph.html")

supporting_files/01_largest_subgraph.html

### **修改结构**

In [7]:
# 获取所有的边
edges1 = list(sm_subgraph.edges)

* 规则1：父节点的时期不应该晚于子节点

In [8]:
# 函数：提取节点名称中的数字部分
def get_time_index(node_name):
    match = re.search(r'(\d+)$', node_name)  # 匹配节点名中的数字部分
    return int(match.group(1)) if match else None

In [9]:
# 遍历所有边，删除不符合因果关系的边
edges_to_remove = []
for parent, child in edges1:
    parent_time = get_time_index(parent)
    child_time = get_time_index(child)
    
    if parent_time is not None and child_time is not None and parent_time > child_time:  # 如果父节点时间序号大于子节点时间序号，删除这条边
        edges_to_remove.append((parent, child))

In [10]:
# 从图中删除这些边
sm_subgraph.remove_edges_from(edges_to_remove)

viz = plot_structure(
    sm_subgraph,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.show("supporting_files/00_modified_structure.html")

supporting_files/00_modified_structure.html

* 规则2：同一时期的出行变量之间的因果路径删除

In [11]:
edges2 = list(sm_subgraph.edges)

In [12]:
# 定义出行变量前缀
travel_cols = [
    'avg_daily_dist', 'avg_daily_dur', 'avg_daily_tube_dist', 'avg_daily_tube_freq',
    'avg_daily_slow_dist', 'avg_daily_slow_freq'
]

In [13]:
# 删除同一时期内出行变量之间的因果路径
edges_to_remove = []
for parent, child in edges2:
    # 检查父节点和子节点是否属于同一时期的变量
    if any(parent.startswith(prefix) for prefix in travel_cols) and any(child.startswith(prefix) for prefix in travel_cols):
        parent_time = get_time_index(parent)
        child_time = get_time_index(child)
        
        # 如果父节点和子节点属于同一时期，删除这条边
        if parent_time is not None and child_time is not None and parent_time == child_time:
            edges_to_remove.append((parent, child))

In [14]:
# 从图中删除这些边
sm_subgraph.remove_edges_from(edges_to_remove)

viz = plot_structure(
    sm_subgraph,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.show("supporting_files/00_modified_structure.html")

supporting_files/00_modified_structure.html

In [30]:
list(sm_area_subgraph.edges)

[('area0', 'area2'),
 ('area0', 'area3'),
 ('area0', 'avg_daily_slow_dist0'),
 ('area0', 'avg_daily_slow_dist1'),
 ('area1', 'area2'),
 ('area1', 'area3'),
 ('area1', 'avg_daily_slow_dist1'),
 ('home_density_0', 'avg_daily_tube_freq0'),
 ('work_landusemix_0', 'work_road_density_0'),
 ('work_landusemix_0', 'work_bus_0'),
 ('work_openratio_wide_0', 'work_landusemix_0'),
 ('work_openratio_wide_0', 'work_road_density_0'),
 ('work_openratio_wide_0', 'work_bus_0'),
 ('work_subway_0', 'work_bus_0'),
 ('work_subway_0', 'avg_daily_tube_dist0'),
 ('work_subway_0', 'avg_daily_tube_freq0'),
 ('work_subway_0', 'avg_daily_tube_freq1'),
 ('work_subway_0', 'avg_daily_tube_freq2'),
 ('work_subway_0', 'avg_daily_tube_freq3'),
 ('commute_distance_0', 'area3'),
 ('commute_distance_0', 'avg_daily_dist0'),
 ('commute_distance_0', 'avg_daily_dist1'),
 ('commute_distance_0', 'avg_daily_dist2'),
 ('commute_distance_0', 'avg_daily_dist3'),
 ('commute_distance_0', 'avg_daily_dur0'),
 ('commute_distance_0', 'avg_daily_dur1'),
 ('commute_distance_0', 'avg_daily_slow_freq0'),
 ('commute_distance_0', 'avg_daily_slow_freq1'),
 ('commute_distance_0', 'avg_daily_tube_dist0'),
 ('commute_distance_0', 'avg_daily_tube_dist1'),
 ('commute_distance_0', 'avg_daily_tube_dist2'),
 ('commute_distance_0', 'avg_daily_tube_dist3'),
 ('commute_distance_0', 'avg_daily_tube_freq0'),
 ('commute_distance_0', 'avg_daily_tube_freq1'),
 ('home_density_1', 'area3'),
 ('home_subway_1', 'work_subway_1'),
 ('work_density_1', 'area3'),
 ('work_landusemix_1', 'work_bus_1'),
 ('work_road_density_1', 'work_bus_1'),
 ('work_openratio_wide_1', 'work_landusemix_1'),
 ('work_openratio_wide_1', 'work_road_density_1'),
 ('work_openratio_wide_1', 'work_bus_1'),
 ('work_subway_1', 'work_bus_1'),
 ('work_subway_1', 'avg_daily_tube_freq1'),
 ('work_subway_1', 'avg_daily_tube_freq2'),
 ('work_subway_1', 'avg_daily_tube_freq3'),
 ('commute_distance_1', 'avg_daily_dist1'),
 ('commute_distance_1', 'avg_daily_dist2'),
 ('commute_distance_1', 'avg_daily_dist3'),
 ('commute_distance_1', 'avg_daily_dur2'),
 ('commute_distance_1', 'avg_daily_dur3'),
 ('commute_distance_1', 'avg_daily_slow_freq2'),
 ('commute_distance_1', 'avg_daily_slow_freq3'),
 ('commute_distance_1', 'avg_daily_tube_dist1'),
 ('commute_distance_1', 'avg_daily_tube_dist2'),
 ('commute_distance_1', 'avg_daily_tube_dist3'),
 ('commute_distance_1', 'avg_daily_tube_freq2'),
 ('commute_distance_1', 'avg_daily_tube_freq3'),
 ('avg_daily_dist0', 'avg_daily_dist2'),
 ('avg_daily_dist0', 'avg_daily_dist3'),
 ('avg_daily_dist0', 'avg_daily_dur2'),
 ('avg_daily_dist0', 'avg_daily_dur3'),
 ('avg_daily_dist0', 'avg_daily_tube_dist1'),
 ('avg_daily_dist1', 'avg_daily_dist2'),
 ('avg_daily_dist1', 'avg_daily_dist3'),
 ('avg_daily_dist1', 'avg_daily_dur2'),
 ('avg_daily_dist1', 'avg_daily_dur3'),
 ('avg_daily_dur0', 'avg_daily_dist1'),
 ('avg_daily_dur0', 'avg_daily_dur1'),
 ('avg_daily_dur0', 'avg_daily_dur2'),
 ('avg_daily_dur0', 'avg_daily_dur3'),
 ('avg_daily_dur0', 'avg_daily_slow_dist1'),
 ('avg_daily_dur1', 'avg_daily_dist2'),
 ('avg_daily_dur1', 'avg_daily_dur2'),
 ('avg_daily_dur1', 'avg_daily_dur3'),
 ('avg_daily_dur1', 'avg_daily_slow_dist2'),
 ('avg_daily_dur2', 'avg_daily_dist3'),
 ('avg_daily_dur2', 'avg_daily_slow_dist3'),
 ('avg_daily_dur2', 'avg_daily_slow_freq3'),
 ('avg_daily_slow_dist0', 'avg_daily_slow_dist1'),
 ('avg_daily_slow_dist0', 'avg_daily_slow_dist2'),
 ('avg_daily_slow_dist1', 'avg_daily_slow_dist2'),
 ('avg_daily_slow_dist2', 'area2'),
 ('avg_daily_slow_dist2', 'area3'),
 ('avg_daily_slow_dist3', 'area3'),
 ('avg_daily_slow_freq0', 'avg_daily_slow_dist1'),
 ('avg_daily_slow_freq0', 'avg_daily_slow_dist2'),
 ('avg_daily_slow_freq0', 'avg_daily_slow_dist3'),
 ('avg_daily_slow_freq0', 'avg_daily_slow_freq1'),
 ('avg_daily_slow_freq0', 'avg_daily_slow_freq2'),
 ('avg_daily_slow_freq1', 'avg_daily_slow_dist2'),
 ('avg_daily_slow_freq1', 'avg_daily_slow_dist3'),
 ('avg_daily_slow_freq1', 'avg_daily_slow_freq2'),
 ('avg_daily_slow_freq2', 'avg_daily_slow_dist3'),
 ('avg_daily_tube_dist0', 'avg_daily_tube_dist2'),
 ('avg_daily_tube_freq0', 'avg_daily_tube_dist1'),
 ('avg_daily_tube_freq0', 'avg_daily_tube_dist2'),
 ('avg_daily_tube_freq0', 'avg_daily_tube_freq2'),
 ('avg_daily_tube_freq1', 'avg_daily_tube_freq2'),
 ('avg_daily_tube_freq2', 'avg_daily_tube_dist3'),
 ('avg_daily_tube_freq3', 'area3')]

* 规则3：删除avg_daily_dist, avg_daily_tube_dist, avg_daily_slow_dist试试

In [15]:
# 获取所有边
edges3 = list(sm_subgraph.edges)

In [16]:
# 定义需要删除的列名
remove_columns = ['avg_daily_dist', 'avg_daily_tube_dist', 'avg_daily_slow_dist']

# 筛选出与 'avg_daily_dist', 'avg_daily_tube_dist', 'avg_daily_slow_dist' 相关的边
edges_to_remove = [(parent, child) for parent, child in edges3 if any(col in parent for col in remove_columns) or any(col in child for col in remove_columns)]

In [17]:
# 删除这些边
sm_subgraph.remove_edges_from(edges_to_remove)

# 重新获取最大子图
sm_subgraph = sm_subgraph.get_largest_subgraph()

# 可视化更新后的图形并保存为 HTML 文件
viz = plot_structure(
    sm_subgraph,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.show("supporting_files/00_modified_structure.html")

supporting_files/00_modified_structure.html

* 规则4：添加边（area2->area3; cluster2->cluster3）

In [18]:
sm_subgraph.add_edge("area2", "area3")
sm_subgraph.add_edge("cluster2", "cluster3")

In [19]:
# 可视化更新后的图形并保存为 HTML 文件
viz = plot_structure(
    sm_subgraph,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.show("supporting_files/00_modified_structure.html")

supporting_files/00_modified_structure.html

### 导出结构

In [47]:
import networkx as nx

nx.drawing.nx_pydot.write_dot(sm_subgraph, 'supporting_files/graph.dot')

### Cluster Causal Path

In [50]:
sm_cluster = from_pandas(df_cluster, tabu_parent_nodes=['cluster2','cluster3'])

In [51]:
weight_thre = 0.03

In [52]:
sm_cluster.remove_edges_below_threshold(weight_thre)

viz = plot_structure(
    sm_cluster,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)
# viz.toggle_physics(False)
viz.show("supporting_files/02_thresholded.html")

supporting_files/02_thresholded.html

**最大子图**

In [53]:
sm_cluster_subgraph = sm_cluster.get_largest_subgraph()
viz = plot_structure(
    sm_cluster_subgraph,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)
viz.show("supporting_files/02_largest_subgraph.html")

supporting_files/02_largest_subgraph.html

**修改结构**

In [128]:
# 获取所有的边
edges1 = list(sm_cluster_subgraph.edges)
edges1

[('cluster0', 'cluster2'),
 ('cluster0', 'cluster3'),
 ('cluster1', 'cluster0'),
 ('cluster1', 'cluster2'),
 ('cluster1', 'cluster3'),
 ('home_density_0', 'work_density_0'),
 ('home_density_0', 'married'),
 ('work_road_density_0', 'work_landusemix_0'),
 ('work_road_density_0', 'work_openratio_wide_0'),
 ('work_bus_0', 'work_landusemix_0'),
 ('work_bus_0', 'work_subway_0'),
 ('commute_distance_0', 'avg_daily_tube_freq0'),
 ('commute_distance_0', 'avg_daily_tube_freq1'),
 ('work_road_density_1', 'work_landusemix_1'),
 ('work_road_density_1', 'work_openratio_wide_1'),
 ('work_bus_1', 'work_landusemix_1'),
 ('work_bus_1', 'work_subway_1'),
 ('commute_distance_1', 'cluster2'),
 ('commute_distance_1', 'cluster3'),
 ('commute_distance_1', 'avg_daily_tube_freq3'),
 ('gender', 'cluster0'),
 ('gender', 'cluster1'),
 ('gender', 'cluster2'),
 ('gender', 'cluster3'),
 ('gender', 'age'),
 ('gender', 'income'),
 ('gender', 'state'),
 ('age', 'cluster0'),
 ('age', 'cluster1'),
 ('age', 'cluster2'),
 ('age', 'cluster3'),
 ('age', 'income'),
 ('age', 'state'),
 ('edu', 'married'),
 ('edu', 'income'),
 ('income', 'cluster0'),
 ('income', 'cluster1'),
 ('income', 'cluster2'),
 ('income', 'cluster3'),
 ('income', 'state'),
 ('state', 'cluster0'),
 ('state', 'cluster1'),
 ('state', 'cluster2'),
 ('state', 'cluster3'),
 ('avg_daily_dist0', 'commute_distance_0'),
 ('avg_daily_dist0', 'avg_daily_dist1'),
 ('avg_daily_dist0', 'avg_daily_dur0'),
 ('avg_daily_dist0', 'avg_daily_dur1'),
 ('avg_daily_dist0', 'avg_daily_dur2'),
 ('avg_daily_dist0', 'avg_daily_dur3'),
 ('avg_daily_dist1', 'commute_distance_0'),
 ('avg_daily_dist1', 'avg_daily_dur0'),
 ('avg_daily_dist1', 'avg_daily_dur1'),
 ('avg_daily_dist1', 'avg_daily_dur2'),
 ('avg_daily_dist1', 'avg_daily_dur3'),
 ('avg_daily_dist2', 'cluster2'),
 ('avg_daily_dist2', 'commute_distance_1'),
 ('avg_daily_dist2', 'avg_daily_dist0'),
 ('avg_daily_dist2', 'avg_daily_dist1'),
 ('avg_daily_dist2', 'avg_daily_dur0'),
 ('avg_daily_dist2', 'avg_daily_dur1'),
 ('avg_daily_dist2', 'avg_daily_dur2'),
 ('avg_daily_dist2', 'avg_daily_dur3'),
 ('avg_daily_dist2', 'avg_daily_tube_dist3'),
 ('avg_daily_dist3', 'cluster2'),
 ('avg_daily_dist3', 'cluster3'),
 ('avg_daily_dist3', 'commute_distance_1'),
 ('avg_daily_dist3', 'avg_daily_dist2'),
 ('avg_daily_dist3', 'avg_daily_dur0'),
 ('avg_daily_dist3', 'avg_daily_dur1'),
 ('avg_daily_dist3', 'avg_daily_dur2'),
 ('avg_daily_dist3', 'avg_daily_dur3'),
 ('avg_daily_dur0', 'avg_daily_slow_dist0'),
 ('avg_daily_dur0', 'avg_daily_slow_dist1'),
 ('avg_daily_dur1', 'avg_daily_slow_dist0'),
 ('avg_daily_dur1', 'avg_daily_slow_dist1'),
 ('avg_daily_dur1', 'avg_daily_slow_freq1'),
 ('avg_daily_dur2', 'avg_daily_dur0'),
 ('avg_daily_dur2', 'avg_daily_dur1'),
 ('avg_daily_dur2', 'avg_daily_dur3'),
 ('avg_daily_dur2', 'avg_daily_slow_dist2'),
 ('avg_daily_dur2', 'avg_daily_slow_dist3'),
 ('avg_daily_dur2', 'avg_daily_slow_freq2'),
 ('avg_daily_dur3', 'avg_daily_dur0'),
 ('avg_daily_dur3', 'avg_daily_dur1'),
 ('avg_daily_dur3', 'avg_daily_slow_dist2'),
 ('avg_daily_dur3', 'avg_daily_slow_dist3'),
 ('avg_daily_dur3', 'avg_daily_slow_freq3'),
 ('avg_daily_slow_dist0', 'avg_daily_slow_freq0'),
 ('avg_daily_slow_dist0', 'avg_daily_slow_freq1'),
 ('avg_daily_slow_dist1', 'avg_daily_slow_dist0'),
 ('avg_daily_slow_dist1', 'avg_daily_slow_freq0'),
 ('avg_daily_slow_dist1', 'avg_daily_slow_freq1'),
 ('avg_daily_slow_dist2', 'avg_daily_slow_dist0'),
 ('avg_daily_slow_dist2', 'avg_daily_slow_dist1'),
 ('avg_daily_slow_dist2', 'avg_daily_slow_dist3'),
 ('avg_daily_slow_dist2', 'avg_daily_slow_freq2'),
 ('avg_daily_slow_dist2', 'avg_daily_slow_freq3'),
 ('avg_daily_slow_dist3', 'avg_daily_slow_freq2'),
 ('avg_daily_slow_dist3', 'avg_daily_slow_freq3'),
 ('avg_daily_slow_freq1', 'avg_daily_slow_freq0'),
 ('avg_daily_slow_freq2', 'avg_daily_slow_freq1'),
 ('avg_daily_slow_freq2', 'avg_daily_slow_freq3'),
 ('avg_daily_tube_dist0', 'commute_distance_0'),
 ('avg_daily_tube_dist0', 'avg_daily_tube_freq0'),
 ('avg_daily_tube_dist0', 'avg_daily_tube_freq1'),
 ('avg_daily_tube_dist1', 'commute_distance_0'),
 ('avg_daily_tube_dist1', 'avg_daily_dist1'),
 ('avg_daily_tube_dist1', 'avg_daily_tube_freq1'),
 ('avg_daily_tube_dist2', 'commute_distance_1'),
 ('avg_daily_tube_dist2', 'avg_daily_tube_dist1'),
 ('avg_daily_tube_dist2', 'avg_daily_tube_dist3'),
 ('avg_daily_tube_dist2', 'avg_daily_tube_freq2'),
 ('avg_daily_tube_dist2', 'avg_daily_tube_freq3'),
 ('avg_daily_tube_dist3', 'commute_distance_1'),
 ('avg_daily_tube_dist3', 'avg_daily_tube_freq3'),
 ('avg_daily_tube_freq0', 'work_subway_0'),
 ('avg_daily_tube_freq0', 'avg_daily_tube_freq1'),
 ('avg_daily_tube_freq2', 'work_subway_1'),
 ('avg_daily_tube_freq2', 'avg_daily_tube_freq1'),
 ('avg_daily_tube_freq2', 'avg_daily_tube_freq3'),
 ('avg_daily_tube_freq3', 'cluster3')]

In [129]:
# 函数：提取节点名称中的数字部分
def get_time_index(node_name):
    match = re.search(r'(\d+)$', node_name)  # 匹配节点名中的数字部分
    return int(match.group(1)) if match else None

In [133]:
# 遍历所有边，删除不符合因果关系的边（时序性）
edges_to_remove = []
for parent, child in edges1:
    parent_time = get_time_index(parent)
    child_time = get_time_index(child)
    
    if parent_time is not None and child_time is not None and parent_time > child_time:  # 如果父节点时间序号大于子节点时间序号，删除这条边
        edges_to_remove.append((parent, child))

In [134]:
# 从图中删除这些边
sm_cluster_subgraph.remove_edges_from(edges_to_remove)

viz = plot_structure(
    sm_cluster_subgraph,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.show("supporting_files/02_modified_structure.html")

supporting_files/02_modified_structure.html

In [137]:
edges2 = list(sm_cluster_subgraph.edges)

In [136]:
# 定义出行变量前缀
travel_cols = [
    'avg_daily_dist', 'avg_daily_dur', 'avg_daily_tube_dist', 'avg_daily_tube_freq',
    'avg_daily_slow_dist', 'avg_daily_slow_freq'
]

In [139]:
# 删除同一时期内出行变量之间的因果路径
edges_to_remove = []
for parent, child in edges2:
    # 检查父节点和子节点是否属于同一时期的变量
    if any(parent.startswith(prefix) for prefix in travel_cols) and any(child.startswith(prefix) for prefix in travel_cols):
        parent_time = get_time_index(parent)
        child_time = get_time_index(child)
        
        # 如果父节点和子节点属于同一时期，删除这条边
        if parent_time is not None and child_time is not None and parent_time == child_time:
            edges_to_remove.append((parent, child))

In [140]:
# 从图中删除这些边
sm_cluster_subgraph.remove_edges_from(edges_to_remove)

viz = plot_structure(
    sm_cluster_subgraph,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

viz.show("supporting_files/02_modified_structure.html")

supporting_files/02_modified_structure.html

In [141]:
list(sm_cluster_subgraph.edges)

[('cluster0', 'cluster2'),
 ('cluster0', 'cluster3'),
 ('cluster1', 'cluster2'),
 ('cluster1', 'cluster3'),
 ('home_density_0', 'work_density_0'),
 ('home_density_0', 'married'),
 ('work_road_density_0', 'work_landusemix_0'),
 ('work_road_density_0', 'work_openratio_wide_0'),
 ('work_bus_0', 'work_landusemix_0'),
 ('work_bus_0', 'work_subway_0'),
 ('commute_distance_0', 'avg_daily_tube_freq0'),
 ('commute_distance_0', 'avg_daily_tube_freq1'),
 ('work_road_density_1', 'work_landusemix_1'),
 ('work_road_density_1', 'work_openratio_wide_1'),
 ('work_bus_1', 'work_landusemix_1'),
 ('work_bus_1', 'work_subway_1'),
 ('commute_distance_1', 'cluster2'),
 ('commute_distance_1', 'cluster3'),
 ('commute_distance_1', 'avg_daily_tube_freq3'),
 ('gender', 'cluster0'),
 ('gender', 'cluster1'),
 ('gender', 'cluster2'),
 ('gender', 'cluster3'),
 ('gender', 'age'),
 ('gender', 'income'),
 ('gender', 'state'),
 ('age', 'cluster0'),
 ('age', 'cluster1'),
 ('age', 'cluster2'),
 ('age', 'cluster3'),
 ('age', 'income'),
 ('age', 'state'),
 ('edu', 'married'),
 ('edu', 'income'),
 ('income', 'cluster0'),
 ('income', 'cluster1'),
 ('income', 'cluster2'),
 ('income', 'cluster3'),
 ('income', 'state'),
 ('state', 'cluster0'),
 ('state', 'cluster1'),
 ('state', 'cluster2'),
 ('state', 'cluster3'),
 ('avg_daily_dist0', 'commute_distance_0'),
 ('avg_daily_dist0', 'avg_daily_dist1'),
 ('avg_daily_dist0', 'avg_daily_dur1'),
 ('avg_daily_dist0', 'avg_daily_dur2'),
 ('avg_daily_dist0', 'avg_daily_dur3'),
 ('avg_daily_dist1', 'avg_daily_dur2'),
 ('avg_daily_dist1', 'avg_daily_dur3'),
 ('avg_daily_dist2', 'cluster2'),
 ('avg_daily_dist2', 'avg_daily_dur3'),
 ('avg_daily_dist2', 'avg_daily_tube_dist3'),
 ('avg_daily_dist3', 'cluster3'),
 ('avg_daily_dur0', 'avg_daily_slow_dist1'),
 ('avg_daily_dur2', 'avg_daily_dur3'),
 ('avg_daily_dur2', 'avg_daily_slow_dist3'),
 ('avg_daily_slow_dist0', 'avg_daily_slow_freq1'),
 ('avg_daily_slow_dist2', 'avg_daily_slow_dist3'),
 ('avg_daily_slow_dist2', 'avg_daily_slow_freq3'),
 ('avg_daily_slow_freq2', 'avg_daily_slow_freq3'),
 ('avg_daily_tube_dist0', 'commute_distance_0'),
 ('avg_daily_tube_dist0', 'avg_daily_tube_freq1'),
 ('avg_daily_tube_dist2', 'avg_daily_tube_dist3'),
 ('avg_daily_tube_dist2', 'avg_daily_tube_freq3'),
 ('avg_daily_tube_freq0', 'work_subway_0'),
 ('avg_daily_tube_freq0', 'avg_daily_tube_freq1'),
 ('avg_daily_tube_freq2', 'avg_daily_tube_freq3'),
 ('avg_daily_tube_freq3', 'cluster3')]

In [11]:
# from IPython.display import display, HTML
# %matplotlib widget
# sm = StructureModel()
# sm.add_edges_from([
#     ('health', 'absences'),
#     ('health', 'G1')
# ])
# viz = plot_structure(
#     sm,
#     all_node_attributes=NODE_STYLE.WEAK,
#     all_edge_attributes=EDGE_STYLE.WEAK,
# )
# viz.show("supporting_files/01_simple_plot.html")
# # display(HTML("supporting_files/01_simple_plot.html"))

supporting_files/01_simple_plot.html